# Generated by Django 5.1.2 on 2024-11-18 13:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('news', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Recipe',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255, verbose_name='Название рецепта')),
                ('ingredients', models.TextField(verbose_name='Ингредиенты')),
                ('instruction', models.TextField(verbose_name='Инструкция для приготовления')),
                ('prep_time', models.IntegerField(verbose_name='Время приготовления в минутах')),
                ('is_vegetarian', models.BooleanField(verbose_name='Вегатарианское блюдо?')),
                ('created_at', models.DateField(auto_now_add=True, verbose_name='Дата добавления предмета')),
            ],
            options={
                'verbose_name_plural': 'Рецепты',
            },
        ),
        migrations.DeleteModel(
            name='News',
        ),
    ]
