# Generated by Django 5.1.2 on 2024-11-27 12:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('news', '0002_alter_todo_user'),
    ]

    operations = [
        migrations.AlterField(
            model_name='todo',
            name='is_comleted',
            field=models.BooleanField(blank=True, null=True, verbose_name='Выполнено'),
        ),
    ]
