# Generated by Django 5.1.2 on 2024-11-22 14:37

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('news', '0004_remove_recipe_category_students_transaction_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='students',
            name='geekcoin',
            field=models.IntegerField(default=0, verbose_name='Количество Geek coin'),
        ),
        migrations.AlterField(
            model_name='transaction',
            name='fromuser',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='хз', to=settings.AUTH_USER_MODEL),
        ),
        migrations.RemoveField(
            model_name='transaction',
            name='touser',
        ),
        migrations.AddField(
            model_name='transaction',
            name='touser',
            field=models.ForeignKey(default=4, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
            preserve_default=False,
        ),
    ]
