# Generated by Django 5.1.2 on 2024-11-22 16:28

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('auth', '0012_alter_user_first_name_max_length'),
        ('news', '0006_alter_students_geekcoin'),
    ]

    operations = [
        migrations.AlterField(
            model_name='students',
            name='groups',
            field=models.ManyToManyField(blank=True, help_text='The groups this user belongs to.', related_name='student_groups', to='auth.group', verbose_name='groups'),
        ),
        migrations.AlterField(
            model_name='students',
            name='user_permissions',
            field=models.ManyToManyField(blank=True, help_text='Specific permissions for this user.', related_name='student_permissions', to='auth.permission', verbose_name='user permissions'),
        ),
        migrations.AlterField(
            model_name='transaction',
            name='fromuser',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='хз', to='news.students'),
        ),
        migrations.AlterField(
            model_name='transaction',
            name='touser',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='news.students'),
        ),
    ]
