# Generated by Django 5.1.2 on 2024-11-23 05:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('auth', '0012_alter_user_first_name_max_length'),
        ('news', '0007_alter_students_groups_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='students',
            name='groups',
            field=models.ManyToManyField(blank=True, help_text='The groups this user belongs to.', related_name='students_groups', related_query_name='student', to='auth.group', verbose_name='groups'),
        ),
        migrations.AlterField(
            model_name='students',
            name='user_permissions',
            field=models.ManyToManyField(blank=True, help_text='Specific permissions for this user.', related_name='students_permissions', related_query_name='student', to='auth.permission', verbose_name='user permissions'),
        ),
    ]
