# Generated by Django 5.1.2 on 2024-11-22 11:55

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Authors',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255, unique=True, verbose_name='Имя автора')),
                ('birthdate', models.DateField(verbose_name='День рождения автора')),
            ],
            options={
                'verbose_name_plural': 'Авторы',
            },
        ),
        migrations.CreateModel(
            name='Books',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.TextField(verbose_name='Название книги')),
                ('publication_year', models.DateField(verbose_name='Год издания')),
                ('authors', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Books.authors')),
            ],
            options={
                'verbose_name_plural': 'Книги',
            },
        ),
        migrations.CreateModel(
            name='Genre',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255, verbose_name='Название жанра')),
                ('books', models.ManyToManyField(to='Books.books')),
            ],
            options={
                'verbose_name_plural': 'Жанры',
            },
        ),
    ]
